#### Numpy(Numerical Python):
 - NumPy is a Python library used for fast numerical computing. It provides support for multi-dimensional arrays, mathematical functions, linear algebra operations, random number generation, and tools for handling large datasets efficiently. Its array structure (ndarray) is optimised for performance, making it much faster than standard Python lists for numerical tasks.

In [1]:
import numpy as np #alias -> np

 - **Scalar**: A single numerical value without dimensions.
 - **Vector**: A one-dimensional collection of numbers.
 - **Matrix**: A two-dimensional structured arrangement of numbers.
 - **Tensor**: A multi-dimensional generalization of vectors and matrices.

#### Understanding Dimensions in NumPy (Bracket Pattern)

 ###### [] → If there is 1 pair of brackets, it is a 1D array.

 ###### [[ ]] → If there are 2 pairs of brackets, it is a 2D array.

 ###### [[[ ]]] → If there are 3 pairs of brackets, it is a 3D array.

 ###### [[[[ ]]]] → If there are 4 pairs of brackets, it is a 4D array.

And so on… each extra pair of brackets increases the dimension by 1.

In [2]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

**ndim**: means the number of dimensions of an array. It tells how many axes the array has. 
<br>**arr.ndim**: returns that dimension count.<br>

In [3]:
arr.ndim

1

In [4]:
arr =np.array(34)
arr.ndim

0

In [5]:
a = np.array([[[[]]]])
a.ndim
a.shape

(1, 1, 1, 0)

#### arange()
**np.arange()**: creates an array by generating values starting from the first number, stopping before the second number, and increasing by the step value given as the third argument.

In [6]:
range = np.arange(1,10, 2) #(start, stop, step)
range

array([1, 3, 5, 7, 9])

#### linspace()
**np.linspace()** creates an array of evenly spaced values between the start and end points.
The third argument specifies how many values should be generated in total.

In [7]:
arr = np.linspace(0,1,10) # (start, stop, number of values)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

The **retstep=True** in np.linspace() returns the step size between consecutive values along with the array of evenly spaced numbers. By default it is **False**.

In [8]:
arr = np.linspace(0,1,10, retstep = True) 
arr

(array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ]),
 np.float64(0.1111111111111111))

#### logspace()
**np.logspace()** creates an array of numbers that are evenly spaced on a logarithmic scale, between the specified start and end values. The third argument specifies how many values should be generated in total.

In [9]:
arr = np.logspace(1, 3, 2)        #logarithmic scale array -> 10^1 -> 10^3 ... 3 points
arr                               # np.logspace(start, ending -> powers, 3 -> number of values)

array([  10., 1000.])

#### zeros()
**np.zeros()** creates an array filled entirely with zeros.
The argument specifies the shape of the array (how many rows and columns or dimensions it should have).

In [10]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [11]:
arr = np.zeros([2,3]) 
arr


array([[0., 0., 0.],
       [0., 0., 0.]])

#### ones()
**np.ones()** creates an array filled entirely with ones. The argument specifies the shape of the array (how many rows, columns, or dimensions it should have).

In [12]:
arr = np.ones([4,2]) 
arr

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

#### full()
**np.full()** creates an array filled with a value you specify.
The first argument defines the shape, and the second argument defines the constant value to fill the entire array with.

In [13]:
arr = np.full(10, 2) #-> create an array full of any value
arr

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
arr = np.full([2,4], 7.1) #[row, column], default value
arr

array([[7.1, 7.1, 7.1, 7.1],
       [7.1, 7.1, 7.1, 7.1]])

#### empty()
**np.empty()** creates an array with a given shape but does not initialize its values.
The elements contain whatever values already existed in memory, so the array may hold random or garbage values.

In [15]:
arr = np.empty([2,3]) #Uninitialized array -> create an array without setting any values
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

#### random.rand()
**np.random.rand()** creates an array with a given shape and initializes it with random values between 0 and 1, sampled from a uniform distribution.

In [16]:
arr = np.random.rand(10)
arr #-> random floats(0 to 1)

array([0.02622158, 0.06305873, 0.57523161, 0.72702575, 0.51395298,
       0.527088  , 0.80999849, 0.16423976, 0.12662708, 0.51897602])

In [17]:
arr = np.random.rand(2,3)
arr

array([[0.60657718, 0.66889373, 0.08962021],
       [0.34990423, 0.16845615, 0.16081984]])

#### random.randn()
**np.random.randn()** generates an array of random values sampled from a standard normal distribution (mean = 0, standard deviation = 1). The shape of the array is determined by the arguments passed.

In [18]:
arr = np.random.randn(2,3)
arr                                 #-> random floats from the standard normal distribution

array([[-0.84257862, -0.49207395, -0.54479663],
       [ 1.56957566,  1.34142462,  0.11476123]])

#### random.randint()
**np.random.randint()** generates an array of random integers within a specified range. You can define both the lower and upper limits of the range, as well as the size of the array.

In [19]:
arr = np.random.randint(10, 100)     #->start, stop, dimension/number of values
arr                                  #-> random integers

60

In [20]:
arr = np.random.randint(10, 100, size = (2,3))   #->start, stop, dimension/number of values
arr

array([[39, 80, 21],
       [11, 12, 14]], dtype=int32)

## Numpy Data Types and Type Casting

In [21]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

 - **NumPy arrays** require all elements to have the same data type. When an array contains both **integers** and **floats**, NumPy promotes all elements to **float** to preserve precision, as **floats** can represent both **whole numbers** and **decimals**.

In [22]:
arr = np.array([1,2,3.1,4,5])
arr

array([1. , 2. , 3.1, 4. , 5. ])

In [23]:
arr.dtype

dtype('float64')

In [24]:
type(arr)

numpy.ndarray

 - NumPy arrays require all elements to have the same data type. Type promotion: When an array contains elements of 
different types, NumPy promotes all elements to the highest data type to maintain consistency. In this case, since 
there is a string ("string") in the array; all other elements (integers and floats) are promoted to strings.

In [25]:
lst = ["string", 1, 2, 5.6]
arr = np.array(lst)
arr

array(['string', '1', '2', '5.6'], dtype='<U32')

In [26]:
arr = np.array(["1",2,3.1,4,5])
arr

array(['1', '2', '3.1', '4', '5'], dtype='<U32')

In [27]:
arr.dtype

dtype('<U32')

 - We can also convert our **float** data type in **int**

In [28]:
arr = np.array([1.1, 2.6 , 3 , 4], dtype = np.int64)

In [29]:
arr.dtype

dtype('int64')

In [30]:
arr

array([1, 2, 3, 4])

 - **Type casting** is the process of converting data from one type to another. It can be done using the **astype()** method in many programming languages, such as Python, to explicitly convert data types.

In [31]:
arr = np.array([1,2,3])
arr.dtype

dtype('int64')

In [32]:
new_arr = arr.astype(np.float64)
new_arr

array([1., 2., 3.])

#### or

In [33]:
new_arr = arr.astype(float)
new_arr

array([1., 2., 3.])

In [34]:
new_arr.dtype

dtype('float64')

In [35]:
new_arr2 = new_arr.astype(np.int64)
new_arr2

array([1, 2, 3])

 - The **error** occurs because the array contains **non-numeric** values (like **"hello"**), which cannot be converted to integers using **astype(np.int64).** However, if the array contains only **strings** that represent valid **integers** (like **'2'**), then **arr.astype(np.int64)** would work **without error.**

In [148]:
# Type Casting errors:

arr = np.array(["1", "2", "hello"])
arr2 = arr.astype(np.int64)
arr2


ValueError: invalid literal for int() with base 10: np.str_('hello')

In [37]:
arr = np.array([[1,2,3],
                [4,5,6]])

In [38]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
arr.ndim

2

 - **a.shape** : Returns a tuple representing the dimensions of the array.

In [40]:
arr.shape

(2, 3)

 - **a.size** : Returns the total number of elements in the array.

In [41]:
arr.size

6

 - **a.itemsize** : Returns the size (in bytes) of each element in the array.

In [42]:
arr.itemsize

8

#### Array Reshaping: Reshape, Ravel, flatten

**reshape()** is used to change the shape of an existing NumPy array without changing its data.
 - **Note** : The total number of elements must remain the same in the new shape.

In [43]:
# Reshape
arr = np.array([1,2,3,4,5,6])
reshaped = arr.reshape(2,3)
print(reshaped)

[[1 2 3]
 [4 5 6]]


In [44]:
reshape2 = reshaped.reshape(3,2)

In [45]:
reshape2

array([[1, 2],
       [3, 4],
       [5, 6]])

 - **ravel()** : Flattens a NumPy array into a 1D array and returns a view of the original data if possible.

     - Modifying the result of **ravel()** might affect the original array, depending on whether a copy was made. 
 - **flatten()** : Flattens a NumPy array into a 1D array and returns a copy of the data.

     - Modifying the result of **ravel()** might affect the original array, depending on whether a copy was made.

**Difference** : ravel() returns a view (if possible), while flatten() always returns a new copy of the data.

In [46]:
#ravel -> convert 1D array
ravel = reshape2.ravel()
ravel

array([1, 2, 3, 4, 5, 6])

In [47]:
ravel[0] = 100
print(ravel)
print(reshape2)

[100   2   3   4   5   6]
[[100   2]
 [  3   4]
 [  5   6]]


In [48]:
#flatten -> to 1D array
# -> returns a copy of the array

flat = reshape2.flatten()
flat

array([100,   2,   3,   4,   5,   6])

In [49]:
flat[0] = 1

In [50]:
flat

array([1, 2, 3, 4, 5, 6])

In [51]:
reshape2

array([[100,   2],
       [  3,   4],
       [  5,   6]])

# Arithmetic Operations on Arrays

In [52]:
a = np.array([1,2,3])
b = np.array([4,5,6])


#### addition:

In [53]:
print(a+b)

[5 7 9]


#### subtraction

In [54]:
print(b-a)

[3 3 3]


#### division:

In [55]:
print(a/b)

[0.25 0.4  0.5 ]


 - **Integer division** is the division of two integers that returns the quotient without the remainder, truncating the result to an integer.

In [56]:
print(b//a)

[4 2 2]


#### multiplication

In [57]:
print(a*b)

[ 4 10 18]


 - **Modulus** is the operation that returns the remainder after dividing one number by another.

In [58]:
print(b%a)

[0 1 0]


#### exponent:- power

In [59]:
print(a**2)

[1 4 9]


### Universal Function -> ufuncs

In [60]:
arr = np.array([1,4,9,16])

#### Square root : np.sqrt()

In [61]:
print(np.sqrt(arr))

[1. 2. 3. 4.]


#### exponential : np.exp : e^x : x is any integer

In [62]:
print(np.exp([1,2]))

[2.71828183 7.3890561 ]


#### sine function : np.sin

In [63]:
angles = np.array([0, np.pi/2, np.pi])
print(np.sin(angles))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]


### Indexing and Slicing

 - Indexing is the process of accessing a specific element in a sequence (like a list, string, or array) using its position or index.

 - Slicing is the process of extracting a sub-sequence from a sequence by specifying a range of indices.

In [64]:
a = [1,2,3,4,5]

In [65]:
a[-1:-4: -1]

[5, 4, 3]

In [66]:
a[: :2]

[1, 3, 5]

In [67]:
arr = np.array([10,20,30,40,50])
# indexes = 0, 2, 4
arr[::2]

array([10, 30, 50])

#### Negative Indexing

In [68]:
print(arr[-1])

50


In [69]:
matrix = np.array([[1,2,3],
                  [4,5,6],
                  [7,8,9]])

In [70]:
print(matrix[0:2, 0:2])

[[1 2]
 [4 5]]


In [71]:
print(matrix[0:2, :])

[[1 2 3]
 [4 5 6]]


In [72]:
print(matrix[1: , 1:])

[[5 6]
 [8 9]]


- **np.take()** is a NumPy function that retrieves elements from an array based on specified indices, and it can operate along a particular axis if needed.

In [73]:
arr = np.array([10,20,30,40,50])
ind = [0, 2]
print(np.take(arr, ind))

[10 30]


In [74]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result_2d = np.take(arr_2d, [0, 2], axis=0)
result_2d

array([[1, 2, 3],
       [7, 8, 9]])

In [75]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
result_3d = np.take(arr_3d, [0, 1], axis=1)
result_3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

#### Iteration with np.nditer()
 - **np.nditer()** is a NumPy iterator object used to iterate over an array, allowing efficient and flexible looping over elements, including support for multiple dimensions and advanced iteration strategies.

In [76]:
arr= np.array([[1,2], [3,4]])

In [77]:
for x in np.nditer(arr):
  print(x, end = " ")

1 2 3 4 

In [78]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

for x, y in np.nditer([arr1, arr2]):
    print(x, y)

1 4
2 5
3 6


 - **np.ndenumerate()** is a NumPy function that returns an iterator that gives both the index and value for each element in a multi-dimensional array.

In [79]:
for ind, x in np.ndenumerate(arr):
  print(ind, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


 - **view :** A view is a new array that references the same data as the original array, so changes affect both.

In [80]:
arr = np.array([1,2,3,4,5])
new = arr[1:3].view()
new

array([2, 3])

In [81]:
new[0] = 200

In [82]:
new

array([200,   3])

In [83]:
arr

array([  1, 200,   3,   4,   5])

- **copy :** A copy creates a new array with its own data, so changes do not affect the original array.

In [84]:
copy = arr[1:3].copy()
copy

array([200,   3])

In [85]:
copy[0] = 2
copy

array([2, 3])

In [86]:
arr

array([  1, 200,   3,   4,   5])

In [87]:
arr = np.array([[1,2], [3,4]])
arr

array([[1, 2],
       [3, 4]])

 - **transpose()** is a NumPy function that returns a new array with the dimensions of the original array swapped (rows become columns and columns become rows).

In [88]:
print(arr.transpose())

[[1 3]
 [2 4]]


 - **swapaxes()** is a NumPy function that swaps two specified axes of an array. It allows you to change the order of the dimensions in a multi-dimensional array.

In [89]:
arr = np.array([[[1,2], [3,4]]])
arr.shape

(1, 2, 2)

In [90]:
swap = np.swapaxes(arr, 0, 1)
swap.shape

(2, 1, 2)

 - **concatenate()** in NumPy refers to combining two or more arrays along a specified axis. It is commonly used to join arrays together.

In [91]:
a = np.array([1,2])
b = np.array([3,4])

In [92]:
combine = np.concatenate((a,b))
combine

array([1, 2, 3, 4])

 - **np.vstack()** is a NumPy function used to stack arrays vertically (along rows). It takes a sequence of arrays and stacks them on top of each other, essentially concatenating them along the first axis (axis=0).

In [93]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[5,6], [7,8]])

In [94]:
print(np.vstack((arr1, arr2)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


 - **np.hstack()** is a NumPy function used to stack arrays horizontally (along columns). It is essentially a shorthand for concatenating arrays along axis=1.

In [95]:
print(np.hstack((arr1, arr2)))

[[1 2 5 6]
 [3 4 7 8]]


 - **np.stack()** is a NumPy function used to stack arrays along a new axis. It differs from functions like np.concatenate(), np.hstack(), and np.vstack() because it adds a new dimension to the stacked arrays.

In [96]:
print(np.stack((arr1, arr2), axis = 0))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [97]:
print(np.stack((arr1, arr2), axis = 1))

[[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]


#### Splitting Arrays:

In [98]:
arr1 = np.array([[1,2], [3,4], [5,6], [7,8]])

In [99]:
arr1

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

 - **np.split()** is a NumPy function used to split an array into multiple sub-arrays. You can split the array either by specifying the number of splits or the indices where the splits should occur.

In [100]:
print(np.split(arr1, 4))

[array([[1, 2]]), array([[3, 4]]), array([[5, 6]]), array([[7, 8]])]


 - **np.hsplit()** is a NumPy function used to split an array into multiple sub-arrays horizontally (along columns). It is similar to np.split(), but specifically for splitting along the horizontal axis (i.e., axis=1).

In [101]:
print(np.hsplit(arr1, 2))

[array([[1],
       [3],
       [5],
       [7]]), array([[2],
       [4],
       [6],
       [8]])]


#### Repeating:

 - **np.repeat()** is a NumPy function used to repeat elements of an array along a specified axis. You can repeat elements of the array multiple times either along a specific axis or across the entire array.

In [102]:
arr = np.array([1,2,3])
print(np.repeat(arr,3))

[1 1 1 2 2 2 3 3 3]


 - **np.tile()** is a NumPy function that repeats an array a specified number of times along each axis, essentially creating a larger array by replicating the original array.

In [103]:
print(np.tile(arr, 3))

[1 2 3 1 2 3 1 2 3]


#### Aggregate Functions:

 - **np.sum() :** Computes the sum of array elements over a specified axis or the entire array.

 - **np.mean() :** Calculates the arithmetic mean (average) of array elements along the specified axis or over the entire array.

 - **np.median() :** Returns the median (middle value) of array elements along the specified axis or over the entire array.

 - **np.std() :** Computes the standard deviation, which measures the spread of elements from the mean.

 - **np.var() :** Calculates the variance, which measures the squared spread of array elements from the mean.

 - **np.max() :** Returns the maximum value from the array or along a specified axis.

 - **np.min() :** Returns the minimum value from the array or along a specified axis.

In [104]:
arr = np.array([1,2,3])
print(np.sum(arr))

6


In [105]:
np.mean(arr)

np.float64(2.0)

In [106]:
np.median(arr)

np.float64(2.0)

In [107]:
np.std(arr)

np.float64(0.816496580927726)

In [108]:
np.var(arr)

np.float64(0.6666666666666666)

In [109]:
np.max(arr)

np.int64(3)

In [110]:
np.min(arr)

np.int64(1)

In [111]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [112]:
print(np.sum(matrix, axis = 0))

[12 15 18]


#### Cumulative Operations

In [113]:
arr =np.array([1,3,2,6,2])
arr

array([1, 3, 2, 6, 2])

 - **np.cumsum() :** Computes the cumulative sum of array elements along a specified axis.

In [114]:
print(np.cumsum(arr))

[ 1  4  6 12 14]


 - **np.cumprod() :** Computes the cumulative product of array elements along a specified axis.

In [115]:
print(np.cumprod(arr))

[ 1  3  6 36 72]


 - **np.minimum.accumulate() :** Computes the cumulative minimum of array elements, progressively keeping track of the smallest value encountered up to each position.

 - **np.maximum.accumulate() :** Computes the cumulative maximum of array elements, progressively keeping track of the largest value encountered up to each position.

In [116]:
print(np.minimum.accumulate(arr))

[1 1 1 1 1]


In [117]:
print(np.maximum.accumulate(arr))

[1 3 3 6 6]


### Conditional-based choices

 - **np.where()** is a NumPy function that returns the indices of array elements that satisfy a given condition, or it can be used for element-wise selection between two arrays based on a condition.

In [118]:
arr

array([1, 3, 2, 6, 2])

In [119]:
result = np.where(arr <2, "low", "high")

In [120]:
result

array(['low', 'high', 'high', 'high', 'high'], dtype='<U4')

In [121]:
arr

array([1, 3, 2, 6, 2])

 - **np.argwhere()** is a NumPy function that returns the indices of array elements that satisfy a given condition, as a list of coordinate pairs (for multi-dimensional arrays).

In [122]:
arr =np.array([21, 32, 43, 10, 9])
arr

array([21, 32, 43, 10,  9])

In [123]:
print(np.argwhere(arr > 30))

[[1]
 [2]]


In [124]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
print(np.argwhere(matrix> 5))

[[1 2]
 [2 0]
 [2 1]
 [2 2]]


 - The **logical AND** in NumPy, implemented by **np.logical_and(),** returns **True** for elements where both conditions are **True,** element-wise across arrays.

In [126]:
arr

array([21, 32, 43, 10,  9])

In [127]:
new_arr = np.logical_and(arr > 20, arr < 30)
new_arr

array([ True, False, False, False, False])

In [128]:
arr[new_arr]

array([21])

 - The **logical OR** in NumPy, implemented by **np.logical_or(),** returns **True** for elements where at least one of the conditions is **True,** element-wise across arrays.

In [129]:
new_arr = np.logical_or(arr < 30, arr > 40)
new_arr

array([ True, False,  True,  True,  True])

In [130]:
arr[new_arr]

array([21, 43, 10,  9])

 - **np.nonzero()** is a NumPy function that returns the indices of the elements in an array that are **non-zero,** i.e., it identifies the positions where the array elements are **non-zero.** The result is returned as a tuple of arrays (one for each dimension).

In [131]:
arr2 = np.array([0, 1, 5, 0, 5])
arr2

array([0, 1, 5, 0, 5])

In [132]:
print(np.nonzero(arr2))

(array([1, 2, 4]),)


 - **Broadcasting** in NumPy refers to the ability to perform arithmetic operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger array, without copying data.

**Broadcasting Rules (Very Important)**

NumPy compares the shapes of the arrays from the end (right to left) and follows these rules:

 - If shapes are equal, they're compatible.

 - If one is 1, it can be stretched to match the other.

 - If shapes are different and not 1 or equal → Error.

**In simpler terms:**

 - If the last dimension is the same or one of the arrays has a size of 1, broadcasting works.

 - If the shapes don't align and aren't compatible, broadcasting will raise an error.

In [133]:
image = np.array([[200, 150], [100, 250]])
image.shape

(2, 2)

In [134]:
brightness = image + 50
brightness

array([[250, 200],
       [150, 300]])

In [135]:
 # np.vectorize() -> convert a regular function to be applied on an array.

 - **Vectorization** in NumPy refers to performing operations on entire arrays without using explicit loops, resulting in faster and more efficient code by leveraging optimized C-based functions.

In [136]:
def square(x):
  return x*x

vfunc = np.vectorize(square)

In [137]:
arr

array([21, 32, 43, 10,  9])

In [138]:
print(vfunc(arr))

[ 441 1024 1849  100   81]


**Dealing With Missing values:**

 - **np.nan :** Represents "Not a Number," used to indicate undefined or missing values in an array.

 - **np.inf :** Represents positive infinity, used for values larger than any finite number.

 - **np.inf :** Represents negative infinity, used for values smaller than any finite number.

 - **np.isnan() :** Checks if elements in an array are NaN (Not a Number). Returns a boolean array where True represents NaN.
 - **np.isinf() :** Checks if elements in an array are infinite (positive or negative infinity). Returns a boolean array where True represents inf or -inf.
 - **np.isfinite() :** Checks if elements in an array are finite (not NaN, inf, or -inf). Returns a boolean array where True represents finite numbers.

**These are the functions used to detect any null values, infinite value, or finite value**

In [139]:
a = np.array([1, 2, np.nan, 4])

In [140]:
a

array([ 1.,  2., nan,  4.])

In [141]:
print(np.isnan(a))

[False False  True False]


In [142]:
b = np.array([1, np.nan, np.inf, 10.2, 40])

In [143]:
print(np.isinf(b))

[False False  True False False]


In [144]:
c = a = np.array([1, 2, np.nan, np.inf, 4])
c

array([ 1.,  2., nan, inf,  4.])

In [145]:
result = (np.logical_or(np.isnan(c), np.isinf(c)))
result

array([False, False,  True,  True, False])

**remove Nan/ infinite values**

 - **nan_to_num()** is a function in NumPy that replaces NaN (Not a Number) values with a specified numerical value (typically 0) and also handles infinite values by replacing them with large finite numbers. It ensures that arrays with NaNs or infinities can be used in calculations without errors.

In [146]:
new_b = np.nan_to_num(b)

In [147]:
new_b

array([1.00000000e+000, 0.00000000e+000, 1.79769313e+308, 1.02000000e+001,
       4.00000000e+001])